using System;
using System.Text;
using UnityEngine;
using UnityEngine.Networking;

namespace Texy
{
    /// <summary>
    /// The optional AI generation engine. It posts the (augmented) prompt to a configurable
    /// text-to-image REST endpoint and decodes the returned image. Color maps (albedo, emission,
    /// decal) come straight from the model with map-specific prompt engineering; data maps
    /// (normal, AO, height, roughness, metallic) are generated by first producing an AI albedo and
    /// then running the same <see cref="MapPostProcessor"/> derivations the procedural engine uses,
    /// so the whole map set stays consistent. Supports OpenAI-compatible and SD-WebUI response shapes.
    /// </summary>
    public class AITextureProvider : ITextureProvider
    {
        public string Name => "AI (prompt-to-image)";

        private readonly TexySettings _settings;
        public AITextureProvider(TexySettings settings) { _settings = settings; }

        public bool IsReady(out string reason)
        {
            if (string.IsNullOrEmpty(_settings.AiEndpoint))
            {
                reason = "No AI endpoint configured (set one in Settings).";
                return false;
            }
            if (_settings.AiResponse == TexySettings.AiResponseFormat.OpenAI && string.IsNullOrEmpty(_settings.AiApiKey))
            {
                reason = "No API key configured for the OpenAI-compatible endpoint.";
                return false;
            }
            reason = null;
            return true;
        }

        public void Generate(TextureRequest request, Action<float, string> onProgress, Action<TextureResult> onComplete)
        {
            if (!IsReady(out string reason))
            {
                onComplete?.Invoke(TextureResult.Fail(reason, request.MapType, Name));
                return;
            }

            var style = PromptParser.Parse(request.Prompt, request.Mesh);

            // Data maps need a base albedo first, then a deterministic CPU derivation.
            if (RequiresDerivation(request.MapType))
            {
                onProgress?.Invoke(0.05f, "Requesting AI base color...");
                RequestImage(AugmentPrompt(request.Prompt, MapType.Albedo, style), request,
                    onProgress,
                    albedo =>
                    {
                        onProgress?.Invoke(0.75f, "Deriving " + MapTypeInfo.DisplayName(request.MapType) + "...");
                        Texture2D derived = Derive(request, style, albedo);
                        UnityEngine.Object.DestroyImmediate(albedo);
                        onComplete?.Invoke(TextureResult.Ok(derived, request.MapType, Name));
                    },
                    err => onComplete?.Invoke(TextureResult.Fail(err, request.MapType, Name)));
                return;
            }

            // Color maps come directly from the model.
            onProgress?.Invoke(0.05f, "Contacting AI endpoint...");
            RequestImage(AugmentPrompt(request.Prompt, request.MapType, style), request,
                onProgress,
                tex =>
                {
                    if (request.MapType == MapType.Decal)
                        tex = LuminanceToAlpha(tex);
                    onComplete?.Invoke(TextureResult.Ok(tex, request.MapType, Name));
                },
                err => onComplete?.Invoke(TextureResult.Fail(err, request.MapType, Name)));
        }

        private static bool RequiresDerivation(MapType type)
        {
            switch (type)
            {
                case MapType.Normal:
                case MapType.Height:
                case MapType.AmbientOcclusion:
                case MapType.Roughness:
                case MapType.Smoothness:
                case MapType.Metallic:
                    return true;
                default:
                    return false;
            }
        }

        private Texture2D Derive(TextureRequest req, PromptParser.TextureStyle style, Texture2D albedo)
        {
            int w = req.Width, h = req.Height;
            switch (req.MapType)
            {
                case MapType.Normal:
                {
                    var height = MapPostProcessor.AlbedoToHeight(albedo, w, h);
                    return Finalize(MapPostProcessor.HeightToNormal(height, w, h, req.Strength), w, h, linear: true);
                }
                case MapType.Height:
                {
                    var height = MapPostProcessor.AlbedoToHeight(albedo, w, h);
                    return Finalize(MapPostProcessor.HeightToGrayscale(height, w, h), w, h, linear: true);
                }
                case MapType.AmbientOcclusion:
                {
                    var height = MapPostProcessor.AlbedoToHeight(albedo, w, h);
                    return Finalize(MapPostProcessor.HeightToAO(height, w, h, req.Strength), w, h, linear: true);
                }
                case MapType.Metallic:
                    return Finalize(MapPostProcessor.ConstantGray(w, h, Mathf.Clamp01(style.Metallic)), w, h, linear: true);
                case MapType.Roughness:
                    return Finalize(MapPostProcessor.ConstantGray(w, h, Mathf.Clamp01(style.Roughness)), w, h, linear: true);
                case MapType.Smoothness:
                    return Finalize(MapPostProcessor.ConstantGray(w, h, Mathf.Clamp01(1f - style.Roughness)), w, h, linear: true);
                default:
                    return albedo;
            }
        }

        // ---- prompt engineering per map ----
        private static string AugmentPrompt(string prompt, MapType type, PromptParser.TextureStyle style)
        {
            string baseDesc = string.IsNullOrWhiteSpace(prompt) ? DescribeStyle(style) : prompt.Trim();
            switch (type)
            {
                case MapType.Albedo:
                    return $"Seamless tileable PBR base color (albedo) texture of {baseDesc}. Flat even lighting, no shadows, no highlights, no ambient occlusion baked in, orthographic top-down, high detail, photorealistic material surface.";
                case MapType.Emission:
                    return $"Seamless tileable emission/glow map of {baseDesc}. Pure black background, only the glowing parts are bright and colored, high contrast.";
                case MapType.Decal:
                    return $"A single isolated decal/tattoo design of {baseDesc}, centered on a pure black background, clean edges, high contrast, no border.";
                default:
                    return baseDesc;
            }
        }

        private static string DescribeStyle(PromptParser.TextureStyle style)
        {
            return $"{style.Material.ToString().ToLowerInvariant()} surface with a {style.Pattern.ToString().ToLowerInvariant()} pattern";
        }

        // ---- networking ----
        private void RequestImage(string prompt, TextureRequest req, Action<float, string> onProgress,
            Action<Texture2D> onImage, Action<string> onError)
        {
            int size = Mathf.Clamp(Mathf.Max(req.Width, req.Height), 256, 2048);
            string body = BuildRequestBody(prompt, size, req.Tileable);

            var www = new UnityWebRequest(_settings.AiEndpoint, "POST");
            byte[] payload = Encoding.UTF8.GetBytes(body);
            www.uploadHandler = new UploadHandlerRaw(payload);
            www.downloadHandler = new DownloadHandlerBuffer();
            www.SetRequestHeader("Content-Type", "application/json");
            if (!string.IsNullOrEmpty(_settings.AiApiKey))
                www.SetRequestHeader("Authorization", "Bearer " + _settings.AiApiKey);
            www.timeout = Mathf.Max(30, _settings.AiTimeoutSeconds);

            EditorWebRequest.Send(www,
                done =>
                {
                    if (done.result != UnityWebRequest.Result.Success)
                    {
                        onError?.Invoke($"Request failed ({done.responseCode}): {done.error}\n{Truncate(done.downloadHandler.text, 400)}");
                        return;
                    }
                    HandleResponse(done.downloadHandler.text, req, onProgress, onImage, onError);
                },
                p => onProgress?.Invoke(0.1f + p * 0.6f, "Generating image..."));
        }

        // Quality guard-rails for texture work: keep models from baking in lighting, borders or artifacts.
        private const string TextureNegativePrompt =
            "shadow, baked lighting, highlight, gradient lighting, border, frame, watermark, text, signature, " +
            "blurry, lowres, jpeg artifacts, seams, perspective, vignette";

        private string BuildRequestBody(string prompt, int size, bool tileable)
        {
            string escaped = EscapeJson(prompt);
            if (_settings.AiResponse == TexySettings.AiResponseFormat.SDWebUI)
            {
                // Automatic1111 / Forge: "tiling" makes the result seamless, which is exactly what
                // avatar body/clothing atlases need. "Euler a" is universally available across versions.
                return "{" +
                       $"\"prompt\":\"{escaped}\"," +
                       $"\"negative_prompt\":\"{TextureNegativePrompt}\"," +
                       $"\"steps\":28,\"cfg_scale\":7,\"sampler_name\":\"Euler a\"," +
                       $"\"tiling\":{(tileable ? "true" : "false")}," +
                       $"\"width\":{size},\"height\":{size}" +
                       "}";
            }

            // OpenAI-compatible images endpoint.
            return "{" +
                   $"\"model\":\"{EscapeJson(_settings.AiModel)}\"," +
                   $"\"prompt\":\"{escaped}\"," +
                   $"\"n\":1,\"size\":\"{size}x{size}\",\"response_format\":\"b64_json\"" +
                   "}";
        }

        private void HandleResponse(string json, TextureRequest req, Action<float, string> onProgress,
            Action<Texture2D> onImage, Action<string> onError)
        {
            string key = _settings.AiResponse == TexySettings.AiResponseFormat.SDWebUI ? "images" : "b64_json";
            string b64 = ExtractFirstString(json, key);

            if (!string.IsNullOrEmpty(b64))
            {
                try
                {
                    byte[] bytes = Convert.FromBase64String(StripDataUri(b64));
                    onImage?.Invoke(DecodeAndResize(bytes, req.Width, req.Height));
                }
                catch (Exception e) { onError?.Invoke("Failed to decode image: " + e.Message); }
                return;
            }

            // OpenAI url variant: download the produced image.
            string url = ExtractFirstString(json, "url");
            if (!string.IsNullOrEmpty(url))
            {
                onProgress?.Invoke(0.8f, "Downloading image...");
                var dl = UnityWebRequestTexture.GetTexture(url);
                EditorWebRequest.Send(dl, done =>
                {
                    if (done.result != UnityWebRequest.Result.Success)
                    {
                        onError?.Invoke("Image download failed: " + done.error);
                        return;
                    }
                    var tex = DownloadHandlerTexture.GetContent(done);
                    onImage?.Invoke(ResizeTexture(tex, req.Width, req.Height));
                });
                return;
            }

            onError?.Invoke("Could not find image data in response. First 400 chars:\n" + Truncate(json, 400));
        }

        // ---- image helpers ----
        private static Texture2D DecodeAndResize(byte[] pngOrJpg, int w, int h)
        {
            var tmp = new Texture2D(2, 2, TextureFormat.RGBA32, false);
            tmp.LoadImage(pngOrJpg);
            var resized = ResizeTexture(tmp, w, h);
            UnityEngine.Object.DestroyImmediate(tmp);
            return resized;
        }

        private static Texture2D ResizeTexture(Texture2D src, int w, int h)
        {
            var pixels = MapPostProcessor.ReadResized(src, w, h);
            return Finalize(pixels, w, h, linear: false, alpha: true);
        }

        /// <summary>For decals from models that paint on black: turn black areas transparent.</summary>
        private static Texture2D LuminanceToAlpha(Texture2D tex)
        {
            var pixels = tex.GetPixels();
            for (int i = 0; i < pixels.Length; i++)
            {
                Color c = pixels[i];
                float lum = 0.299f * c.r + 0.587f * c.g + 0.114f * c.b;
                c.a = Mathf.SmoothStep(0.04f, 0.25f, lum);
                pixels[i] = c;
            }
            tex.SetPixels(pixels);
            tex.Apply(true);
            return tex;
        }

        private static Texture2D Finalize(Color[] pixels, int w, int h, bool linear, bool alpha = false)
        {
            var tex = new Texture2D(w, h, alpha ? TextureFormat.RGBA32 : TextureFormat.RGB24, true, linear);
            tex.wrapMode = TextureWrapMode.Repeat;
            tex.SetPixels(pixels);
            tex.Apply(true);
            return tex;
        }

        // ---- tiny JSON utilities (no external dependency) ----

        /// <summary>Find "key" and return the first JSON string value following it. base64/url values contain no quotes.</summary>
        private static string ExtractFirstString(string json, string key)
        {
            if (string.IsNullOrEmpty(json)) return null;
            int k = json.IndexOf("\"" + key + "\"", StringComparison.Ordinal);
            if (k < 0) return null;
            int colon = json.IndexOf(':', k);
            if (colon < 0) return null;

            // Skip whitespace and an optional opening '[' (arrays like "images":[ "..." ]).
            int i = colon + 1;
            while (i < json.Length && (char.IsWhiteSpace(json[i]) || json[i] == '[')) i++;
            if (i >= json.Length || json[i] != '"') return null;
            i++;

            var sb = new StringBuilder();
            while (i < json.Length)
            {
                char c = json[i];
                if (c == '\\' && i + 1 < json.Length) { sb.Append(json[i + 1]); i += 2; continue; }
                if (c == '"') break;
                sb.Append(c);
                i++;
            }
            return sb.ToString();
        }

        private static string StripDataUri(string b64)
        {
            int comma = b64.IndexOf("base64,", StringComparison.Ordinal);
            return comma >= 0 ? b64.Substring(comma + 7) : b64;
        }

        private static string EscapeJson(string s)
        {
            if (string.IsNullOrEmpty(s)) return string.Empty;
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", " ").Replace("\t", " ");
        }

        private static string Truncate(string s, int max)
        {
            if (string.IsNullOrEmpty(s)) return string.Empty;
            return s.Length <= max ? s : s.Substring(0, max) + "…";
        }
    }
}
